// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitrepAPI.DbContexts;

#nullable disable
#pragma warning disable

namespace SitrepAPI.Migrations
{
    [DbContext(typeof(SitrepDbContext))]
    [Migration("20220221145850_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SitrepAPI.Entities.TestClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestClass");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Gender = "Gender-1",
                            Name = "FirstName-1"
                        },
                        new
                        {
                            Id = -2,
                            Gender = "Gender-2",
                            Name = "FirstName-2"
                        },
                        new
                        {
                            Id = -3,
                            Gender = "Gender-3",
                            Name = "FirstName-3"
                        },
                        new
                        {
                            Id = -4,
                            Gender = "Gender-4",
                            Name = "FirstName-4"
                        },
                        new
                        {
                            Id = -5,
                            Gender = "Gender-5",
                            Name = "FirstName-5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
